[op][upsable][build] llvm: Fix build with gcc-13
:Release Notes:
One more fix is needed for some of the builds.

:Detailed Notes:
Fixes:
http://gecko.lge.com:8000/Errors/Details/580976

FAILED: obj/third_party/swiftshader/third_party/llvm-10.0/swiftshader_llvm_support/Signals.o
aarch64-webos-linux-g++  -mcpu=cortex-a72 -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/webruntime/108.0.5359.217-pro.5-r65.0/recipe-sysroot -MMD -MF obj/third_party/swiftshader/third_party/llvm-10.0/swiftshader_llvm_support/Signals.o.d -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_NETWORK_ERROR_PAGE_CONTROLLER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DENABLE_NETCAST_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DUSE_NEVA_MEDIA=1 -DUSE_NEVA_PUNCH_HOLE=1 -DENABLE_WEBM_AUDIO_CODECS=1 -DUSE_GST_MEDIA=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DUSE_SINGLE_WINDOW_MODE=1 -DWEBOS_SUBMISSION_NUMBER=5 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_LTTNG=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/llvm/include -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/llvm/lib/Target/AArch64 -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/llvm/lib/Target/ARM -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/llvm/lib/Target/Mips -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/llvm/lib/Target/PowerPC -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/llvm/lib/Target/RISCV -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/llvm/lib/Target/X86 -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/configs/common/include -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/configs/common/lib/IR -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/configs/common/lib/Target/AArch64 -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/configs/common/lib/Target/ARM -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/configs/common/lib/Target/Mips -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/configs/common/lib/Target/PowerPC -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/configs/common/lib/Target/RISCV -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/configs/common/lib/Target/X86 -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/configs/common/lib/Transforms/InstCombine -I../../git/src/third_party/swiftshader/third_party/llvm-10.0/configs/linux/include -I../../git/src -Igen -Wno-unused-variable -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -mbranch-protection=standard -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -O2 -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-attributes -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Os -std=gnu++2a -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -Wno-narrowing -Wno-class-memaccess -std=c++17 -c ../../git/src/third_party/swiftshader/third_party/llvm-10.0/llvm/lib/Support/Signals.cpp -o obj/third_party/swiftshader/third_party/llvm-10.0/swiftshader_llvm_support/Signals.o
In file included from ../../git/src/third_party/swiftshader/third_party/llvm-10.0/llvm/lib/Support/Signals.cpp:14:
../../git/src/third_party/swiftshader/third_party/llvm-10.0/llvm/include/llvm/Support/Signals.h:117:8: error: variable or field 'CleanupOnSignal' declared void
  117 |   void CleanupOnSignal(uintptr_t Context);
      |        ^~~~~~~~~~~~~~~
../../git/src/third_party/swiftshader/third_party/llvm-10.0/llvm/include/llvm/Support/Signals.h:117:24: error: 'uintptr_t' was not declared in this scope
  117 |   void CleanupOnSignal(uintptr_t Context);
      |                        ^~~~~~~~~
../../git/src/third_party/swiftshader/third_party/llvm-10.0/llvm/include/llvm/Support/Signals.h:18:1: note: 'uintptr_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   17 | #include <string>
  +++ |+#include <cstdint>
   18 |
In file included from ../../git/src/third_party/swiftshader/third_party/llvm-10.0/llvm/lib/Support/Signals.cpp:220:
../../git/src/third_party/swiftshader/third_party/llvm-10.0/llvm/lib/Support/Unix/Signals.inc:348:44: error: 'void llvm::sys::CleanupOnSignal(uintptr_t)' should have been declared inside 'llvm::sys'
  348 | void sys::CleanupOnSignal(uintptr_t Context) {
      |                                            ^

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-310] Apply .patch files for hot-fix to corresponding repositories
[WRP-13301] Create GPVB with Yocto 4.3 Nanbield

Change-Id: I52b0815c03a575a59120d6ac11b71cf27f157387
Originally-Reviewed-on: http://gpro.lge.com/c/webosose/chromium108/+/352226
Reviewed-on: http://gpro.lge.com/c/webosose/chromium108/+/373250
Reviewed-by: Donghyun Kim <donghyun11.kim@lge.com>
Tested-by: Donghyun Kim <donghyun11.kim@lge.com>