[op][upsable][build] traffic_annotation: fix build with clang-17
:Release Notes:
One more fix is needed for some of the builds.

:Detailed Notes:
Fixes:
FAILED: obj/third_party/blink/renderer/platform/platform/ipc_socket_factory.o
../../git/src/third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/blink/renderer/platform/platform/ipc_socket_factory.o.d -DUSE_WEBOS_AUDIO -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DUSE_NEVA_MEDIA=1 -DUSE_GAV=1 -DUSE_NEVA_MEDIA_PLAYER_CAMERA=1 -DUSE_NEVA_BROWSER_SERVICE=1 -DUSE_WEBRISK_SERVICE=1 -DUSE_WEBRISK_DATABASE=1 -DUSE_NEVA_PUNCH_HOLE=1 -DUSE_NEVA_V4L2_CODEC=1 -DENABLE_WEBM_AUDIO_CODECS=1 -DUSE_GST_MEDIA=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DUSE_NEVA_WEBRTC=1 -DUSE_SINGLE_WINDOW_MODE=1 -DWEBOS_SUBMISSION_NUMBER=2 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_WEBOS_CODEC=1 -DUSE_LTTNG=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-16-init-6578-g0d30e92f-2\" -DCR_SYSROOT_KEY=20220331T153654Z-0 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBLINK_IMPLEMENTATION=1 -DINSIDE_BLINK -DBLINK_PLATFORM_IMPLEMENTATION=1 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DWEBP_EXTERN=extern -DVK_USE_PLATFORM_WAYLAND_KHR -DUSE_EGL -DWTF_USE_WEBAUDIO_PFFFT=1 -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_ENABLE_SKSL -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_WIN_FONTMGR_NO_SIMULATIONS -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_HAS_WUFFS_LIBRARY -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DGOOGLE_PROTOBUF_INTERNAL_DONATE_STEAL_INLINE=0 -DHAVE_PTHREAD -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_DEPRECATION_WARNINGS -DCPPGC_CAGED_HEAP -DCPPGC_YOUNG_GENERATION -DCPPGC_POINTER_COMPRESSION -DWEBRTC_ENABLE_AVX2 -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DWEBRTC_USE_BUILTIN_ISAC_FIX=0 -DWEBRTC_USE_BUILTIN_ISAC_FLOAT=1 -DLOGGING_INSIDE_WEBRTC -DLEVELDB_PLATFORM_CHROMIUM=1 -DUSE_LIBJPEG_TURBO=1 -DFT_CONFIG_MODULES_H=\"freetype-custom/freetype/config/ftmodule.h\" -DFT_CONFIG_OPTIONS_H=\"freetype-custom/freetype/config/ftoption.h\" -DPDFIUM_REQUIRED_MODULES -DCHROMIUM_RESTRICT_VISIBILITY -I../../git/src/third_party/pffft/src -I../../git/src -Igen -I../../git/src/third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../git/src/third_party/libwebp/src/src -Igen/third_party/dawn/include -I../../git/src/third_party/dawn/include -I../../git/src/third_party/khronos -I../../git/src/gpu -I../../git/src/third_party/vulkan-deps/vulkan-headers/src/include -I../../git/src/third_party/libyuv/include -I../../git/src/third_party/jsoncpp/source/include -I../../git/src/third_party/abseil-cpp -I../../git/src/third_party/boringssl/src/include -I../../git/src/third_party/protobuf/src -Igen/protoc_out -I../../git/src/third_party/skia -I../../git/src/third_party/wuffs/src/release/c -I../../git/src/third_party/vulkan/include -I../../git/src/net/third_party/quiche/overrides -I../../git/src/net/third_party/quiche/src/quiche/common/platform/default -I../../git/src/net/third_party/quiche/src -Igen/net/third_party/quiche/src -I../../git/src/third_party/ced/src -I../../git/src/third_party/icu/source/common -I../../git/src/third_party/icu/source/i18n -I../../git/src/v8/include -Igen/v8/include -I../../git/src/third_party/webrtc_overrides -I../../git/src/third_party/webrtc -Igen/third_party/webrtc -I../../git/src/third_party/libwebm/source -I../../git/src/third_party/mesa_headers -I../../git/src/third_party/leveldatabase -I../../git/src/third_party/leveldatabase/src -I../../git/src/third_party/leveldatabase/src/include -I../../git/src/third_party/libaom/source/libaom -I../../git/src/third_party/libjpeg_turbo -I../../git/src/third_party/iccjpeg -I../../git/src/third_party/libpng -I../../git/src/third_party/zlib -I../../git/src/third_party/ots/src/include -I../../git/src/third_party/freetype/include -I../../git/src/third_party/freetype/include/freetype-custom -I../../git/src/third_party/freetype/src/include -I../../git/src/third_party/harfbuzz-ng/src/src -I../../git/src/third_party/emoji-segmenter/src -I../../git/src/third_party/one_euro_filter/src -I../../git/src/third_party/snappy/src -I../../git/src/third_party/snappy/linux -Wno-unused-variable -Wall -Wextra -Wimplicit-fallthrough -Wextra-semi -Wunreachable-code-aggressive -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-ignored-pragma-optimize -Wno-deprecated-builtins -Wno-bitfield-constant-conversion -Wshadow -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../git/src/tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -ffp-contract=off -mbranch-protection=standard --target=aarch64-linux-gnu -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -ffile-compilation-dir=. -no-canonical-prefixes -ftrivial-auto-var-init=pattern -fno-omit-frame-pointer -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang raw-ref-template-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Xclang -add-plugin -Xclang blink-gc-plugin -Xclang -plugin-arg-blink-gc-plugin -Xclang fix-bugs-of-is-considered-abstract -Wconversion -Wno-float-conversion -Wno-sign-conversion -Wno-implicit-float-conversion -Wno-implicit-int-conversion -Wglobal-constructors -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -gdwarf-4 -g1 -gdwarf-aranges -I/OE/lge/build/webos/nanbield/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-2/recipe-sysroot/usr/include/glib-2.0 -I/OE/lge/build/webos/nanbield/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-2/recipe-sysroot/usr/lib/glib-2.0/include -DPROTOBUF_ALLOW_DEPRECATED=1 -I/OE/lge/build/webos/nanbield/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-2/recipe-sysroot/usr/include/nss3 -I/OE/lge/build/webos/nanbield/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-2/recipe-sysroot/usr/include/nspr -std=c++20 -Wno-trigraphs -fno-exceptions -fno-rtti --sysroot=../../recipe-sysroot -fvisibility-inlines-hidden -Wno-deprecated-declarations      -I/OE/lge/build/webos/nanbield/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-2/recipe-sysroot/usr/include/c++/v1       -I/OE/lge/build/webos/nanbield/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-2/recipe-sysroot/usr/include/cbe     -I/OE/lge/build/webos/nanbield/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-2/recipe-sysroot/usr/include/cbe/gmp     -I/OE/lge/build/webos/nanbield/BUILD/work/raspberrypi4_64-webos-linux/webruntime-clang/108.0.5359.217-2/recipe-sysroot/usr/include/media-resource-calculator-clang   -mcpu=cortex-a72 -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type -c ../../git/src/third_party/blink/renderer/platform/p2p/ipc_socket_factory.cc -o obj/third_party/blink/renderer/platform/platform/ipc_socket_factory.o
In file included from ../../git/src/third_party/blink/renderer/platform/p2p/ipc_socket_factory.cc:5:
In file included from ../../git/src/third_party/blink/renderer/platform/p2p/ipc_socket_factory.h:11:
../../git/src/net/traffic_annotation/network_traffic_annotation.h:63:13: error: unknown type name 'size_t'
  template <size_t N1, size_t N2>
            ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:63:24: error: unknown type name 'size_t'
  template <size_t N1, size_t N2>
                       ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:68:13: error: unknown type name 'size_t'
  template <size_t N1, size_t N2>
            ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:68:24: error: unknown type name 'size_t'
  template <size_t N1, size_t N2>
                       ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:74:13: error: unknown type name 'size_t'
  template <size_t N1, size_t N2, size_t N3>
            ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:74:24: error: unknown type name 'size_t'
  template <size_t N1, size_t N2, size_t N3>
                       ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:74:35: error: unknown type name 'size_t'
  template <size_t N1, size_t N2, size_t N3>
                                  ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:112:13: error: unknown type name 'size_t'
  template <size_t N1, size_t N2, size_t N3>
            ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:112:24: error: unknown type name 'size_t'
  template <size_t N1, size_t N2, size_t N3>
                       ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:112:35: error: unknown type name 'size_t'
  template <size_t N1, size_t N2, size_t N3>
                                  ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:152:11: error: unknown type name 'size_t'
template <size_t N1, size_t N2>
          ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:152:22: error: unknown type name 'size_t'
template <size_t N1, size_t N2>
                     ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:176:11: error: unknown type name 'size_t'
template <size_t N1, size_t N2, size_t N3>
          ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:176:22: error: unknown type name 'size_t'
template <size_t N1, size_t N2, size_t N3>
                     ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:176:33: error: unknown type name 'size_t'
template <size_t N1, size_t N2, size_t N3>
                                ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:195:11: error: unknown type name 'size_t'
template <size_t N1, size_t N2>
          ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:195:22: error: unknown type name 'size_t'
template <size_t N1, size_t N2>
                     ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:215:11: error: unknown type name 'size_t'
template <size_t N1, size_t N2, size_t N3>
          ^
../../git/src/net/traffic_annotation/network_traffic_annotation.h:215:22: error: unknown type name 'size_t'
template <size_t N1, size_t N2, size_t N3>
                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-310] Apply .patch files for hot-fix to corresponding repositories
[WRP-13301] Create GPVB with Yocto 4.3 Nanbield

Change-Id: I2abad62733827d873d426bf61e9b5ff366536b52
Reviewed-on: http://gpro.lge.com/c/webosose/chromium108/+/373258
Reviewed-by: Donghyun Kim <donghyun11.kim@lge.com>
Tested-by: Donghyun Kim <donghyun11.kim@lge.com>
Reviewed-by: Jose Dapena Paz <j.dapena@lgepartner.com>
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>