[op][ups][build] avcodec/x86/mathops: clip constants used with shift instructions within inline assembly
:Release Notes:
Fixes assembling with binutil as >= 2.41

:Detailed Notes:
Backported from:
https://git.videolan.org/?p=ffmpeg.git;a=commit;h=25cd95a9dc3510c3cc0d7aad6f9d83f6a1078c7e

Fixes:
http://gecko.lge.com:8000/Errors/Details/651713

FAILED: obj/third_party/ffmpeg/ffmpeg_internal/opus_rc.o
x86_64-webos-linux-gcc  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime/94.0.4606.128-39-r66.2/recipe-sysroot -MMD -MF obj/third_party/ffmpeg/ffmpeg_internal/opus_rc.o.d -DHAVE_AV_CONFIG_H -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -DFFMPEG_CONFIGURATION=NULL -D_ISOC99_SOURCE -D_LARGEFILE_SOURCE -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DUSE_NEVA_MEDIA=1 -DUSE_GAV=1 -DUSE_NEVA_BROWSER_SERVICE=1 -DUSE_WEBRISK_SERVICE=1 -DUSE_NEVA_PUNCH_HOLE=1 -DUSE_GST_MEDIA=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DWEBOS_SUBMISSION_NUMBER=39 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_LTTNG=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../git/src/third_party/ffmpeg/chromium/config/Chrome/linux/x64 -I../../git/src/third_party/ffmpeg -I../../git/src/neva -Igen/neva -I../../git/src -Igen -I../../git/src/third_party/opus/src/include -fPIC -Wno-deprecated-declarations -fomit-frame-pointer -w -std=c99 -pthread -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Wno-unused-variable -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -g0 -fvisibility=hidden -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-attributes -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fdata-sections -ffunction-sections -std=gnu11 -c ../../git/src/third_party/ffmpeg/libavcodec/opus_rc.c -o obj/third_party/ffmpeg/ffmpeg_internal/opus_rc.o
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h: Assembler messages:
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
[4005/43247] CC obj/third_party/ffmpeg/ffmpeg_internal/vorbis_data.o

FAILED: obj/third_party/ffmpeg/ffmpeg_internal/vorbis_parser.o
x86_64-webos-linux-gcc  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime/94.0.4606.128-39-r66.2/recipe-sysroot -MMD -MF obj/third_party/ffmpeg/ffmpeg_internal/vorbis_parser.o.d -DHAVE_AV_CONFIG_H -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -DFFMPEG_CONFIGURATION=NULL -D_ISOC99_SOURCE -D_LARGEFILE_SOURCE -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DUSE_NEVA_MEDIA=1 -DUSE_GAV=1 -DUSE_NEVA_BROWSER_SERVICE=1 -DUSE_WEBRISK_SERVICE=1 -DUSE_NEVA_PUNCH_HOLE=1 -DUSE_GST_MEDIA=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DWEBOS_SUBMISSION_NUMBER=39 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_LTTNG=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../git/src/third_party/ffmpeg/chromium/config/Chrome/linux/x64 -I../../git/src/third_party/ffmpeg -I../../git/src/neva -Igen/neva -I../../git/src -Igen -I../../git/src/third_party/opus/src/include -fPIC -Wno-deprecated-declarations -fomit-frame-pointer -w -std=c99 -pthread -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Wno-unused-variable -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -g0 -fvisibility=hidden -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-attributes -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fdata-sections -ffunction-sections -std=gnu11 -c ../../git/src/third_party/ffmpeg/libavcodec/vorbis_parser.c -o obj/third_party/ffmpeg/ffmpeg_internal/vorbis_parser.o
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h: Assembler messages:
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'

And similarly for 108 version:
http://gecko.lge.com:8000/Errors/Details/651766

FAILED: obj/third_party/ffmpeg/ffmpeg_internal/mpeg4audio.o
x86_64-webos-linux-gcc  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime/108.0.5359.217-pro.23-r66.0/recipe-sysroot -MMD -MF obj/third_party/ffmpeg/ffmpeg_internal/mpeg4audio.o.d -DHAVE_AV_CONFIG_H -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -DFFMPEG_CONFIGURATION=NULL -D_ISOC99_SOURCE -D_LARGEFILE_SOURCE -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_NETWORK_ERROR_PAGE_CONTROLLER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DENABLE_NETCAST_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DENABLE_WEBM_AUDIO_CODECS=1 -DENABLE_WEBM_VIDEO_CODECS=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DUSE_SINGLE_WINDOW_MODE=1 -DWEBOS_SUBMISSION_NUMBER=23 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_LTTNG=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../git/src/third_party/ffmpeg/chromium/config/Chrome/linux/x64 -I../../git/src/third_party/ffmpeg -I../../git/src -Igen -I../../git/src/third_party/opus/src/include -fPIC -Wno-deprecated-declarations -fomit-frame-pointer -w -std=c99 -pthread -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Wno-unused-variable -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -g0 -fvisibility=hidden -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-attributes -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -O2 -fdata-sections -ffunction-sections -std=gnu11 -c ../../git/src/third_party/ffmpeg/libavcodec/mpeg4audio.c -o obj/third_party/ffmpeg/ffmpeg_internal/mpeg4audio.o
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h: Assembler messages:
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'

FAILED: obj/third_party/ffmpeg/ffmpeg_internal/flac_parser.o
x86_64-webos-linux-gcc  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime/108.0.5359.217-pro.23-r66.0/recipe-sysroot -MMD -MF obj/third_party/ffmpeg/ffmpeg_internal/flac_parser.o.d -DHAVE_AV_CONFIG_H -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -DFFMPEG_CONFIGURATION=NULL -D_ISOC99_SOURCE -D_LARGEFILE_SOURCE -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_NETWORK_ERROR_PAGE_CONTROLLER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DENABLE_NETCAST_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DENABLE_WEBM_AUDIO_CODECS=1 -DENABLE_WEBM_VIDEO_CODECS=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DUSE_SINGLE_WINDOW_MODE=1 -DWEBOS_SUBMISSION_NUMBER=23 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_LTTNG=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../git/src/third_party/ffmpeg/chromium/config/Chrome/linux/x64 -I../../git/src/third_party/ffmpeg -I../../git/src -Igen -I../../git/src/third_party/opus/src/include -fPIC -Wno-deprecated-declarations -fomit-frame-pointer -w -std=c99 -pthread -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Wno-unused-variable -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -g0 -fvisibility=hidden -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-attributes -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -O2 -fdata-sections -ffunction-sections -std=gnu11 -c ../../git/src/third_party/ffmpeg/libavcodec/flac_parser.c -o obj/third_party/ffmpeg/ffmpeg_internal/flac_parser.o
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h: Assembler messages:
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'

x86_64-webos-linux-gcc  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=TOPDIR/BUILD/work/qemux86_64-webos-linux/webruntime/108.0.5359.217-pro.23-r66.0/recipe-sysroot -MMD -MF obj/third_party/ffmpeg/ffmpeg_internal/flacdec.o.d -DHAVE_AV_CONFIG_H -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -DFFMPEG_CONFIGURATION=NULL -D_ISOC99_SOURCE -D_LARGEFILE_SOURCE -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_NETWORK_ERROR_PAGE_CONTROLLER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DENABLE_NETCAST_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DENABLE_WEBM_AUDIO_CODECS=1 -DENABLE_WEBM_VIDEO_CODECS=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DUSE_SINGLE_WINDOW_MODE=1 -DWEBOS_SUBMISSION_NUMBER=23 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_LTTNG=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../git/src/third_party/ffmpeg/chromium/config/Chrome/linux/x64 -I../../git/src/third_party/ffmpeg -I../../git/src -Igen -I../../git/src/third_party/opus/src/include -fPIC -Wno-deprecated-declarations -fomit-frame-pointer -w -std=c99 -pthread -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Wno-unused-variable -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -g0 -fvisibility=hidden -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-attributes -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -O2 -fdata-sections -ffunction-sections -std=gnu11 -c ../../git/src/third_party/ffmpeg/libavcodec/flacdec.c -o obj/third_party/ffmpeg/ffmpeg_internal/flacdec.o
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h: Assembler messages:
../../git/src/third_party/ffmpeg/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-20118] Bitbake world issues 2023-07

Change-Id: I4b2a7d26708f4bf5456963c5967f1dad9bb171f4
Signed-off-by: James Almer <jamrial@gmail.com>
Originally-Reviewed-on: http://gpro.lge.com/c/webosose/chromium108/+/363100
Reviewed-on: http://gpro.lge.com/c/webosose/chromium108/+/372657
Reviewed-by: Jose Dapena Paz <j.dapena@lgepartner.com>
Tested-by: Martin Jansa <martin2.jansa@lgepartner.com>
Reviewed-by: Martin Jansa <martin2.jansa@lgepartner.com>
Reviewed-by: Wanchang Ryu <wanchang.ryu@lge.com>
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Reviewed-by: Donghyun Kim <donghyun11.kim@lge.com>